config/routes.rb
Rails.application.routes.draw do

  get 'myaccounts/show'
  get 'myaccounts/edit'
  root "top#index"
  get "about" => "top#about", as: "about"

  resources :members do
    get "search", on: :collection
  end
  # 単数リソース
  resource :session, only: [:create, :destroy]
  resource :myaccount, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]

  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  attachment :image
   
  validates :title, :body, presence: true
  validates :title, length: {maximum: 80 }
  validates :body, length: {maximum: 200 }
  validates :image, presence: true
 
end

app/models/member.rb
class Member < ApplicationRecord
  # パスワード空文字禁止
  has_secure_password

  
  # ニックネーム
  validates :nickname, presence: true,
    length: { minimum: 2, maximum: 20,allow_blank: true},
    uniqueness: { case_sensitive: false}

  # 氏名
  validates :full_name, presence: true, length: { maximum: 20}

  # メールアドレス
  # DBに保存する前にメールアドレスを小文字にする
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # 一意性（メールアドレスが他のユーザーと被らないように）の検証
  validates :email, {presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }}

  # パスワード
  # accessorメソッド（読み書き両用のメソッド）
  attr_accessor :current_password
  # ２行目とは別のvali/新規作成されるときのみ稼働
  validates :password, presence: { if: :current_password }

  # 情報公開（情報公開許可した者だけ選別）
  # scope :common, -> {where(public: "1")}
  
  
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true
  validates :title, length: {maximum: 80 }
  validates :body, length: {maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def current_member
    if session[:member_id] then
      Member.find_by(id: session[:member_id])
    end
  end
  # 引数に指定された名前のメソッドをテンプレートでも
  # 使用できるようにするヘルパーメソッド
  helper_method :current_member

  class LoginRequired < StandardError; end
  class Fobidden < StandardError;end

  private

  def login_required
    raise LoginRequired unless current_member
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # except:コールバック対象外
  before_action :login_required,except: [:index, :show]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: "記事を投稿しました"
    else
      render "new"
    end
  end

  def index
    # idの降順で表示[.order(id: "DESC")]=>asc昇降と迷った場合には
    # reverse_order(新着順）を使用
    @articles = Article.page(params[:page]).reverse_order
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    if @article.save
      redirect_to @article, notice: "記事を更新しました"
    else
      render "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to @article, notice: "記事を削除しました"
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :image)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :login_required

  def index
    # ページネーション付き
    @members = Member.page(params[:page]).reverse_order

  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new(birthday: Date.new(1990, 1, 1))
  end

  def edit
    @member = Member.find(params[:id])
  end

  def create
    @member = Member.new(member_params_create)
    if @member.save
      redirect_to @member, notice: "新しいメンバーを登録しました"
    else
      render "new"
    end
  end

  def update
    @member = Member.find(params[:id])
    @member.update(member_params)
    if @member.save
      redirect_to @member, notice: "メンバー情報を更新しました"
    else
      render "edit"
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to members_path, notice: "メンバーを削除しました"
  end

  def search
    @members = Member.search(params[:q])
    render "index"
  end

  private
  def member_params
      params.require(:member).permit(:nickname, :full_name, :birthday, :email, :administrator)
  end

  def member_params_create
      params.require(:member).permit(:nickname, :full_name, :birthday, :email, :public, :password)
  end
end

app/controllers/myaccounts_controller.rb
class MyaccountsController < ApplicationController
  before_action :login_required

  def show
    @member = current_member
  end

  def edit
    @member = current_member
  end

  def update
    @member = current_member
    @member.update(myaccount_params)
    if @member.save
      redirect_to :myaccount, notice: "マイページを編集しました。"
    else
      render "edit"
    end
  end

  private
  def myaccount_params
    params.require(:myaccount).permit(:nickname, :full_name, :birthday, :email, :public)
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :login_required
  
  def show
    redirect_to :myaccount  
  end
  
  def edit
    @member = current_member
  end 
  
  def update
    @member = current_member
    @member.current_password = params[:myaccount][:current_password]
    
    if current_password.present?
      # 現在のパスが正しいか確認
      if @member.authenticate(current_password)
        # 正しい場合変更
        @member.update(params[:myaccount])
        if @member.save
          redirect_to myaccount_path, notice: "パスワードを変更しました。"
        else 
          render "edit"
        end
      else
        # 誤りの場合
        @member.errors.add(:current_password, :wrong)
        render "edit"
      end
    else
      # 新しいパスが空の場合
      @member.errors.add(:current_password, :empty)
      render "edit"
    end
  end 
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :login_required

  def show
    redirect_to :myaccount
  end

  def edit
    @member = current_member
  end

  def update
    @member = current_member
    current_password = myaccount_params[:current_password]

    if current_password.present?
      # 現在のパスが正しいか確認
      if @member.authenticate(current_password)
        # 正しい場合変更
        @member.update(params[:myaccount])
        if @member.save
          redirect_to myaccount_path, notice: "パスワードを変更しました。"
        else
          render "edit"
        end
      else
        # 誤りの場合
        @member.errors.add(:current_password, :wrong)
        render "edit"
      end
    else
      # 新しいパスが空の場合
      @member.errors.add(:current_password, :empty)
      render "edit"
    end
  end

  private
  def myaccount_params
    params.require(:myaccount).permit(:current_password, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    member = Member.find_by(nickname: params[:nickname])
    if member&.authenticate(params[:password])
      session[:member_id] = member.id
    else
      flash.alert = "名前とパスワードが一致しません"
    end
  redirect_to :root
  end

  def destroy
    session.delete(:member_id)
    redirect_to :root
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = "Memories"
    title = @page_title + "-" + title if @page_title
    title
  end

  def menu_link_to(text, path, options = {})
    content_tag (:li) do
      # :methodに渡されたURLと開いてるページが同じか判別
      condition = options[:method] || !current_page?(path)
      
      link_to_unless_current(text, path, options) do
        content_tag(:span, text)
      end
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/myaccounts_helper.rb
module MyaccountsHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/articles/_form.html.erb
<%= render "common/errors", obj: @article %>

<table class ="attr">
  <tr>
    <th><%= form.label :title %></th>
    <td><%= form.text_field :title, size: 25 %></td>
  </tr>
  <tr>
    <th><%= form.label :body %></th>
    <td><%= form.text_area :body, rows: 10, cols: 30 %></td>
  </tr>
</table>

app/views/articles/edit.html.erb
<% @page_title = "投稿記事の編集" %>

<h1><%= @page_title %></h1>

<div class = "toolbar"><%= link_to "記事の詳細へ戻る", article_path %> </div>

<%= form_with model:@article, local:true do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit "保存" %></div>
<% end %>

app/views/articles/index.html.erb
<% @page_title = "投稿一覧" %>

<h1><%= @page_title %></h1>

<div class="toolbar"><%= link_to "新規投稿", new_article_path %></div>

<% if @articles.present? %>

  <% @articles.each do |article| %>
    <div class="article-item">
      <div class="article-image"><%#= image_tag('img/forest.jpg',  class: 'article-image') %></div>
      <section class="article-text">
        <h3 class="article-text-heading"><%= link_to article.title, article_path(article) %></h3>
        <p class="article-date"><%= article.created_at %></p>
      </section>
    </div>
    <%= link_to "編集", edit_article_path(article.id) %>|
    <%= link_to "削除", article, method: :delete,
        data: {confirm: "本当に削除しますか？"} %>
  <% end %>
  <%= paginate @articles %>
<% else %>
  <p>投稿記事がありません</p>
<% end %>

app/views/articles/new.html.erb
<% @page_title = "新規投稿" %>

<h1><%= @page_title %></h1>
<div class = "toolbar"><%= link_to "投稿一覧に戻る", articles_path %></div>

<%= form_with model:@article, local: true do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit "作成" %></div>
<% end %>

app/views/articles/show.html.erb
<% @page_title = @article.title %>

<h1><%= @article.title %></h1>

<% if current_member %>
  <div class ="toolbar">
    <%= link_to "戻る", articles_path %>|
    <%= link_to "編集", edit_article_path %>|
    <%= link_to "削除", article_path, method: :delete,
        data: {confirm: "本当に削除しますか？"} %>
  </div>
<% end %>

  <section class="single-article">

    <section class="article-box">
      <h3 class="article-box-heading">
        <%= @article.title %>      </h3>
      <div class="article-box-content">
        <p class="article-date">
          <%= @article.created_at %>
        </p>
      </div>
      <%#= image_tag "img/forest.jpg", class:"single-image" %>
      <p class="single-text">
        <%= @article.body %>
      </p>
      <div class="author-case">

app/views/common/_errors.html.erb
<!--objとして範囲を広めてる ◯：present?×：any?-->
<% if obj.errors.present? %>
  <div id ="errors">
    <h3>エラーがあります。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/common/_footer.html.erb
<%= link_to "このサイトについて", about_path %> |
Copyright (C) nozawazawa

app/views/common/_header.html.erb
<%= image_tag "logo.png", size: "200x100", alt: "Memories" %>

<% if current_member %>
<ul class ="account_menu">
  <%= menu_link_to current_member.nickname + "さん", :myaccount %>
  <%= menu_link_to "ログアウト", :session,
        method: :delete, data: { confirm: "ログアウトしますか？" } %>
</ul>
<% end %>

<nav class="menubar">
  <ul>
    <%= menu_link_to "TOP", :root %>
    <!--メンバーのみ閲覧可能にする-->
    <% if current_member %>
      <%= menu_link_to "新着", "#" %>
      <%= menu_link_to "投稿記事", :articles %>
      <%= menu_link_to "メンバー", :members %>
    <% end %>
  </ul>
</nav>

app/views/common/_login_form.html.erb
<h2>ログイン</h2>
<% if flash.alert %>
  <p class ="alert">
    <<%= flash.alert %>
  </p>
<% end %>


<%= form_with url: session_path do |form| %>
  <div>
    <%= form.label :ニックネーム %>
    <%= form.text_field :nickname %>
  </div>
  <div>
    <%= form.label :パスワード %>
    <%= form.text_field :password %>
  </div>
  <div>
    <%= form.submit value="ログイン" %>
  </div>
<% end %>

app/views/common/_member_form.html.erb
<%= render "common/errors", obj: @member%>

<table class ="attr" >
  <tr>
    <th><%= form.label :nickname %></th>
    <td><%= form.text_field :nickname %></td>
  </tr>
  <tr>
    <th><%= form.label :full_name %></th>
    <td><%= form.text_field :full_name %></td>
  </tr>
  <tr>
    <th><%= form.label :birthday, for: "member_birthday_1i" %></th>
    <td><%= form.date_select :birthday,
              start_year: 1990, end_year: Time.current.year,
              use_month_numbers: true %></td>
  </tr>
  <tr>
    <th><%= form.label :email %></th>
    <td><%= form.text_field :email %></td>
  </tr>
  <tr>
    <th>情報公開
    <td><%= form.radio_button :public, 1 %>
      <%= form.label :public_1 %>
      <%= form.radio_button :public, 2 %>
      <%= form.label :public_2 %>
    </td>
  </tr>
  <!--初期パスワード入力のフォーム-->
  <% if @member.new_record? %>
  <tr>
    <th><%= form.label :password, "パスワード" %></th>
    <td><%= form.text_field :password %></td>
  </tr>
  <% end %>
  <!--メンバーコントローラーの時だけチェックボックス表示にするコード-->
  <% if controller.kind_of?(MembersController) %>
  <tr>
    <th><%= Member.human_attribute_name(:administrator) %></th>
    <td>
      <%= form.check_box :administrator,
              disabled: !current_member.administrator? %>
      <%= form.label :administrator %>
    </td>
  </tr>
  <% end %>
  
</table>

app/views/common/_sidebar.html.erb
<%= render "common/login_form" %>

<!--<h2>新着</h2>-->
<!--<ul>-->
<!--  <%# articles.each do |article| %>-->
<!--    <li><%#= link_to article.title, article %></li>-->
<!--  <%# end %>-->
<!--</ul>-->

<!--<h2>メンバーのブログ</h2>-->
<!--<ul>-->

  <!--<%# 5.blogs each do |i| %>-->
  <!--  <li><%#= link_to "ブログの見出し", "#" %></li>-->
  <!--<#% end %>-->



  <!--<%# blogs.each do |blog| %>-->
  <!--  <li>-->
  <!--    <%#= link_to blog.title, blog %>-->
  <!--  </li>-->
  <!--  by <%#= link_to blog.member_id.nickname, [blog.member_id, :blogs] %>-->
  <!--</li>-->
  <!--<%# end %>-->
<!--</ul>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id= "container">
      <header>
        <%= render "common/header" %>
      </header>
      <main>
        <% if flash.notice %>
        <p class ="notice"><%= flash.notice %></p>
        <% end %>
        
        <%= yield %>
      </main>
      <aside id="sidebar">
        <%= render "common/sidebar" %>
      </aside>
      <footer>
        <%= render "common/footer" %>
      </footer>
    </div>
  </body>
</html>

app/views/members/_body.html.erb
<table class ="attr">
  <tr>
    <th>ニックネーム</th>
    <td><%= @member.nickname %></td>
  </tr>
  <tr>
    <th>氏名</th>
    <td><%= @member.full_name %></td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td><%= @member.email %></td>
  </tr>
  <tr>
    <th>誕生日</th>
    <!--&.演算子-->
    <!--誕生日の情報がnilの場合、エラーになるため-->
    <td><%= @member.birthday&.strftime("%Y年%m月%d日") %></td>
  </tr>
  <tr>
    <th>情報公開</th>
    <td><%= @member.public == 1 ? "公開" : "非公開" %></td>
  </tr>
  <tr>
    <th>管理者</th>
    <td><%= @member.administrator? ? "◯" : "ー" %></td>
  </tr>

</table>

app/views/members/_form.html.erb
<%= render "common/errors", obj: @member%>

<table class ="attr" >
  <tr>
    <th><%= form.label :nickname %></th>
    <td><%= form.text_field :nickname %></td>
  </tr>
  <tr>
    <th><%= form.label :full_name %></th>
    <td><%= form.text_field :full_name %></td>
  </tr>
  <tr>
    <th><%= form.label :birthday, for: "member_birthday_1i" %></th>
    <td><%= form.date_select :birthday,
              start_year: 1990, end_year: Time.current.year,
              use_month_numbers: true %></td>
  </tr>
  <tr>
    <th><%= form.label :email %></th>
    <td><%= form.text_field :email %></td>
  </tr>
  <tr>
    <th>情報公開
    <td><%= form.radio_button :public, 1 %>
      <%= form.label :public_1 %>
      <%= form.radio_button :public, 2 %>
      <%= form.label :public_2 %>
    </td>
  </tr>
  <tr>
    <th><%= Member.human_attribute_name(:administrator) %></th>
    <td>
      <%= form.check_box :administrator %>
      <%= form.label :administrator %>
    </td>
  </tr>
  <tr>
    <th><%= form.label :password %></th>
    <td><%= form.text_field :password %></td>
  </tr>
</table>

app/views/members/edit.html.erb
<% @page_title = "会員情報の編集" %>

<h1><%= @page_title %></h1>
<div class ="toolbar">
  <%= link_to "会員の詳細に戻る", @member %>
</div>

<%= form_with model:@member, local: true do |form| %>
  <%= render "common/member_form", form: form %>
  <div><%= form.submit "変更" %></div>
<% end %>

app/views/members/index.html.erb
<% @page_title = "メンバー" %>
<h1><%= @page_title %></h1>

<%= form_tag :search_members, method: :get, class: "search" do %>
  <%= text_field_tag "q", params[:q] %>
  <%= submit_tag "検索" %>
<% end %>

<div class = "toolbar"><%= link_to "新規登録", :new_member %></div>

<% if @members.present? %>
<table class = "list">
  <thead>
    <tr>
      <th>ニックネーム</th>
      <th>氏名</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.nickname, member %></td>
        <td><%= member.full_name %></td>
        <td><%= link_to "編集", edit_member_path(member.id) %>｜
            <%= link_to "削除", member, method: :delete,
                data: { confirm: "本当に削除しますか？" } %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @members %>
<% else %>
  <p>会員情報がありません</p>
<% end %>

app/views/members/new.html.erb
<% @page_title = "新規登録" %>

<h1><%= @page_title %></h1>
<div class = "toolbar"><%= link_to "一覧に戻る", members_path %></div>

<%= form_with model:@member, local: true do |form| %>
  <%= render "common/member_form", form: form %>
  <div><%= form.submit "登録" %></div>
<% end %>

app/views/members/show.html.erb
<% @page_title = "会員の詳細" %>

<h1><%= @page_title %></h1>

<div class ="toolbar">
  <%= link_to "編集", edit_member_path(@member.id) %> |
  <%= link_to "一覧に戻る", members_path %>
</div>

<%= render "body" %>

app/views/myaccounts/edit.html.erb
<% @page_title = "マイページの編集" %>

<h1><%= @page_title %></h1>

<div class ="toolbar">
  <%= link_to "戻る", myaccount_path %>
</div>

<%= form_with model:@member, as: "account", url: myaccount_path, local: true do |form| %>
  <%= render "common/member_form", form: form %>
  <div><%= form.submit value="変更" %></div>
<% end %>

app/views/myaccounts/show.html.erb
<% @page_title = "マイページ" %>

<h1><%= @page_title %></h1>

<div class ="toolbar">
  <%= link_to "マイページの編集", edit_myaccount_path %> |
  <%= link_to "パスワードの変更",edit_password_path %> |
  <%= link_to "一覧に戻る", members_path  %>
</div>

<%= render "members/body" %>

app/views/password/edit.html.erb
<% @page_title = "パスワードの変更" %>

<h1><%= @page_title %></h1>

<div class ="toolbar">
  <%= link_to "マイページに戻る", myaccount_path %>
</div>

<%= form_with model:@member, as: "myaccount", url: password_path, local: true do |form| %>
  <%= render "common/errors", obj: @member %>
  <table class ="attr" >
    <tr>
      <th><%= form.label :current_password %></th>
      <td><%= form.password_field :current_password %></td>
    </tr>
    <tr>
      <th><%= form.label :password %></th>
      <td><%= form.password_field :password %></td>
    </tr>
    <tr>
      <th><%= form.label :password_confirmation %></th>
      <td><%= form.password_field :password_confirmation %></td>
    </tr>
  </table>

  <div><%= form.submit value="変更" %></div>
<% end %>

app/views/top/about.html.erb
<% @page_title = "このサイトについて" %>
<h1><%= @page_title %></h1>
<p>Memoriesは私が所属する特設駅伝チームの画像投稿シェアサイトです。</p>
<p></p>

app/views/top/index.html.erb
<% 5.times do |x| %>
  <h2>見出し</h2>
  <p>
    ここに本文が入ります。ここに本文が入ります。ここに本文が入ります。
    <%= link_to "もっと見る", "#" %>
  </p>
<% end %>